spring:
  application:
    name: springbootfundamentals
stripe:
  apiUrl: https://api.stripe.com
  enabled: true
  timeout: 1000
  supported-currencies: USD,EUR,GBP
payments:
  processor: paypal
email:
  host: gmail
  port: 3000