spring:
  application:
    name: springbootfundamentals
  datasource:
    url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
    username: root
    password: 1234
stripe:
  apiUrl: https://api.stripe.com
  enabled: true
  timeout: 1000
  supported-currencies: USD,EUR,GBP
payments:
  processor: paypal
email:
  host: gmail
  port: 3000